dist: xenial
services:
  - docker
before_install:
  - docker pull miindy/irro-ci:latest
script:
  - >
    docker run
    --volume `pwd`:/root/irro
    --workdir /root/irro
    miindy/irro-ci:latest
    /root/irro/ci/ci.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: html/
  fqdn: irro.mgn.cz
  on:
    branch: master
