dist: xenial
language: python
python: 3.7
install:
  - pip install -r docs/requirements.txt
script:
  - make -C docs
  # Otherwise Travis won't deploy anyting to GitHub Pages
  - rm docs/_build/.gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs/_build
  fqdn: irro.mgn.cz
  on:
    branch: master
