[package]
name = "irro"
version = "0.1.0"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
edition = "2018"

[dependencies]
serialport = "3.2.0"

[lib]
name = "irro"
path = "src/lib.rs"

[[bin]]
name = "irro-cli"
path = "src/main.rs"
